flashrom: run selfcheck on generated SFDP chips
The SFDP-generated chip does not exist at the time of the startup
`selfcheck()`.  Invoke the self check for it later.  This will catch if
the SFDP parser violates any internal contracts, e.g.:

	ERROR: Flash chip SFDP-capable chip erase function 3 is not in order.
	Please report a bug at flashrom@flashrom.org

Change-Id: Ia4a0e68046b2b08671a80378e23474a5ae93ec4b
Signed-off-by: Alex Badea <vamposdecampos@gmail.com>
Reviewed-on: https://review.coreboot.org/c/flashrom/+/90327
Reviewed-by: Anastasia Klimchuk <aklm@chromium.org>
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>