typecast enum conversions explicitly
clang complains like below

libflashrom.c:191:43: error: implicit conversion from enumeration type 'const enum test_state' to different enumeration type 'enum flashrom_test_state' [-Werror,-Wenum-conversion]
                        supported_boards[i].working = binfo[i].working;
                                                    ~ ~~~~~~~~~^~~~~~~
libflashrom.c:229:46: error: implicit conversion from enumeration type 'const enum test_state' to different enumeration type 'enum flashrom_test_state' [-Werror,-Wenum-conversion]
                        supported_chipsets[i].status = chipset[i].status;
                                                     ~ ~~~~~~~~~~~^~~~~~

However these enums are exactly same so they can be typecasted

libflashrom.h

/** @ingroup flashrom-query */
enum flashrom_test_state {
        FLASHROM_TESTED_OK  = 0,
        FLASHROM_TESTED_NT  = 1,
        FLASHROM_TESTED_BAD = 2,
        FLASHROM_TESTED_DEP = 3,
        FLASHROM_TESTED_NA  = 4,
};

flash.h

enum test_state {
          OK = 0,
          NT = 1, /* Not tested */
          BAD,    /* Known to not work */
          DEP,    /* Support depends on configuration (e.g. Intel flash descriptor) */
          NA,     /* Not applicable (e.g. write support on ROM chips) */
  };

Upstream-Status: Pending

Change-Id: If12360e0a2cdbb3cd35bc3c19bdfd74cfe6cac20
Signed-off-by: Khem Raj <raj.khem@gmail.com>