Revert "flashrom.c: move `can_change_target_regions` check below wp unlock"
This reverts commit 3a6d88f4385886298ae0362ee8543725599fdd80.

Reason: tests fail
[  FAILED  ] erase failure for unskipped unwritable regions
[  ERROR   ] --- Blocks allocated...
../libflashrom.c:631: note: block 0x55ede27e51e0 allocated here
ERROR: erase failure for unskipped unwritable regions leaked 1 block(s)

[  FAILED  ] full_chip_erase_with_wp_dummyflasher_test_success
[  ERROR   ] --- Blocks allocated...
../libflashrom.c:631: note: block 0x55ede27e3800 allocated here
../spi25_statusreg.c:312: note: block 0x55ede27e7380 allocated here
ERROR: full_chip_erase_with_wp_dummyflasher_test_success leaked 2 block(s)

Change-Id: I912dab51f7a471d098f6f265aa2582f4194b7b6b
Signed-off-by: Anastasia Klimchuk <aklm@flashrom.org>
Reviewed-on: https://review.coreboot.org/c/flashrom/+/89753
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-by: Stefan Reinauer <stefan.reinauer@coreboot.org>
Reviewed-by: Peter Marheine <pmarheine@chromium.org>