libflashrom: Add flashrom_create_context to create and init context
flashrom_create_context does create and all initialisations
needed for flash context.

The real life usage of flashrom_flash_probe_v2 discovered the issue:
error: variable 'flashctx' has initializer but incomplete type
error: storage size of 'flashctx' isn't known

flashrom_create_context fixes this, it would need to be called prior
to any other api calls that require flash context.

The patch also adds test which runs as external client for
libflashrom.
The test runs in a separate test executable, so that it does not
use flashrom source code but instead uses libflashrom as a
library.
It is also an example how to use libflashrom api.

Change-Id: I483f6cabb2b4ed27e0ee10bf621ae1bddb1fc9f3
Signed-off-by: Anastasia Klimchuk <aklm@flashrom.org>
Reviewed-on: https://review.coreboot.org/c/flashrom/+/89603
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-by: Peter Marheine <pmarheine@chromium.org>